<<<<<<< HEAD
name: Habit Hero Deploy
=======
name: Habit hero Deploy

>>>>>>> 6b0c3ca1bd296e55b627f9fba215a03a7bebc6e8

on:
  push:
    branches: [main]

jobs:
  frontend:
<<<<<<< HEAD
    name: Build & Deploy Frontend
=======
    name: Build & deploy frontend
>>>>>>> 6b0c3ca1bd296e55b627f9fba215a03a7bebc6e8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build React
        working-directory: frontend
        run: |
          npm install
          npm run build
